SET PATH=D:\Keil_v5\ARM\ARMCC\bin\;D:\STMicroelectronics\st_toolset\asm;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;D:\Altium Designer Winter 09\System;D:\Program Files\COSMIC\CXSTM8;D:\Program Files\MATLAB\R2012a\runtime\win32;D:\Program Files\MATLAB\R2012a\bin;
SET CPU_TYPE=STM32F407ZG
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=My_Project
SET CPU_CLOCK=0x00B71B00
"D:\Keil_v5\ARM\ARMCC\bin\ArmAsm" --Via ".\startup_stm32f40_41xxx._ia"
"D:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\misc.__i"
"D:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\stm32f4xx_adc.__i"
"D:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\stm32f4xx_can.__i"
"D:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\stm32f4xx_crc.__i"
"D:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\stm32f4xx_cryp.__i"
"D:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\stm32f4xx_cryp_aes.__i"
"D:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\stm32f4xx_cryp_des.__i"
"D:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\stm32f4xx_cryp_tdes.__i"
